### PR TITLE
7.x 2dev

### PR DESCRIPTION
**Pull request by giancarlobi**
**JIRA Ticket**: (link)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

A brief description of what the intended result of the PR will be and/or what problem it solves.

# What's new?
A in-depth description of the changes made by this PR. Technical details and possible side effects.

Example:
* Changes x feature to such that y
* Added x
* Removed y

# How should this be tested?

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by giancarlobi** [comment]
No sabia bien como hacerlo y si tenia que abrir un ticket, pero como me parece algo solo tuyo experimental, anyway este arreglo hace funcionar el popup info con los metadatos y a lo sumo necesita solo un poco di markup, a ver como te parece

**Review by DiegoPino — APPROVED** [review]

**Comment by giancarlobi** [comment]
The IABR v2 mobile interface is on! some trouble with fullscreen on mobile to make working "hamburger" menu and critical z-index set. Please test it, I tested onto 3 site and all is good. Maybe some makeup to my code needed by @DiegoPino

**Comment by DiegoPino** [comment]
@giancarlobi will review/test your code tomorrow. We could maybe move some of the inline CSS elements out of the code to allow others to override. I also see that the menu bar can be "decorated" instead of overridden completely https://www.sitepoint.com/javascript-decorators-what-they-are/, not sure if that would be a benefit here. 
Thanks for the changes, testing and adding my comments tomorrow! Great work!

**Comment by giancarlobi** [comment]
@DiegoPino you are really much more skilled than me with this code so what you think and suggest is ok for me. I wait your test and if something that I can do I'll happy to apply. Have a nice week.

**Comment by giancarlobi** [comment]
@DiegoPino I made a first IIIF server test. It's working here http://v2p2arch.to.cnr.it/islandora/object/v2p2text%3A55.
Added two new options: 
- ability to enable/disable token in tile source 
- set completely the image tile URL to catch images direct from fedora without go through Islandora proxy.
Several todo: 
- move some settings from theme.inc to IABR admin form
- make image max width used in iiif api url changing dynamically depending on view dimension and for thumbnail view
- add an option to make all as old version (token, djatoka tile source from url)
- check dimensions callback and if we need to get dimensions by iiif  
And could be more after a deep test of this.

**Comment by giancarlobi** [comment]
@DiegoPino as a Views lover ... with few code you can render info tab with Views, I think it's very cool. An example here: http://archive.digibess.eu/islandora/object/librib:83318

**Comment by giancarlobi** [comment]
Another step forward with this great module.
Finally I opted for fixed width to avoid a lot of redrawing, to discuss with @DiegoPino

**Comment by DiegoPino** [comment]
@giancarlobi merging this. Awesome work. Please feel free to keep pushing changes. I will do this week a code cleanup and fix some metadata display + annotations?? issues. great! 🎉

**Pull request merged**
